using System.Reflection;

namespace wl.Services;

public record SetupResult(bool CreateWorkspaceFresh, bool UpdateWorkspaceFresh, string? PreviousVersion, string CurrentVersion);

public class SetupService(WorkspaceService workspaces, VersionService versionService)
{
    private const string CreateSkillName = "wl-create-workspace";
    private const string UpdateSkillName = "wl-update-workspace";

    private static string LoadResource(string name)
    {
        using var stream = Assembly.GetExecutingAssembly()
            .GetManifestResourceStream($"wl.Resources.{name}")
            ?? throw new InvalidOperationException($"Missing embedded resource: {name}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static bool WriteSkill(string skillDir, string resourceName)
    {
        var skillFile = Path.Combine(skillDir, "SKILL.md");
        var existed = File.Exists(skillFile);
        Directory.CreateDirectory(skillDir);
        File.WriteAllText(skillFile, LoadResource(resourceName));
        return !existed;
    }

    private const string DefaultGitignore =
        """
        # Machine-local state — do not sync across PCs
        .last-session
        .last
        .version
        .paths.json

        # wl-managed skills — re-installed by `wl setup` on each PC
        .shared/.claude/skills/wl-create-workspace/
        .shared/.claude/skills/wl-update-workspace/

        # Auto-generated by `wl launch` for Copilot workspaces (mirror of
        # instructions.md — instructions.md is the source of truth)
        */AGENTS.md
        """;

    public SetupResult RunSetup()
    {
        var previous = versionService.GetInstalledVersion();
        var current = versionService.GetCurrentVersion();

        var sharedSkills = workspaces.GetSharedSkillsPath();
        var createDir = Path.Combine(sharedSkills, CreateSkillName);
        var updateDir = Path.Combine(sharedSkills, UpdateSkillName);

        var createFresh = WriteSkill(createDir, $"{CreateSkillName}.md");
        var updateFresh = WriteSkill(updateDir, $"{UpdateSkillName}.md");

        // Migrate from earlier versions that installed wl-create-workspace
        // into the user's global Claude skills dir. wl owns this file; once
        // the new copy is in .shared/.claude/skills/, the legacy global
        // install would just shadow the same skill.
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        var legacyCreateDir = Path.Combine(home, ".claude", "skills", CreateSkillName);
        if (Directory.Exists(legacyCreateDir))
        {
            try { Directory.Delete(legacyCreateDir, recursive: true); }
            catch { /* best effort — user can remove manually if needed */ }
        }

        EnsureGitignore();

        versionService.StampVersion();
        return new SetupResult(createFresh, updateFresh, previous, current);
    }

    private void EnsureGitignore()
    {
        var gitignorePath = Path.Combine(workspaces.GetWorkspacesRoot(), ".gitignore");
        if (!File.Exists(gitignorePath))
        {
            File.WriteAllText(gitignorePath, DefaultGitignore);
        }
    }

    public bool EnsureInstalled()
    {
        if (versionService.GetInstalledVersion() == versionService.GetCurrentVersion())
        {
            return false;
        }

        var result = RunSetup();
        Console.WriteLine();
        Console.WriteLine(result.PreviousVersion is null
            ? "  First run: installed Claude skills."
            : $"  Upgraded {result.PreviousVersion} → {result.CurrentVersion}: refreshed Claude skills.");
        return true;
    }
}
