using System.Reflection;
using System.Text.Json;
using System.Text.Json.Nodes;

using wl.Helpers;
using wl.Models;

namespace wl.Services;

public record SetupResult(bool CreateWorkspaceFresh, bool UpdateWorkspaceFresh, string? PreviousVersion, string CurrentVersion);

public class SetupService(VersionService versionService, WlPaths paths, ConfigService config)
{
    private const string CreateSkillName = "wl-create-workspace";
    private const string UpdateSkillName = "wl-update-workspace";

    private static string LoadResource(string name)
    {
        using var stream = Assembly.GetExecutingAssembly()
            .GetManifestResourceStream($"wl.Resources.{name}")
            ?? throw new InvalidOperationException($"Missing embedded resource: {name}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static bool WriteSkill(string skillDir, string resourceName)
    {
        var skillFile = Path.Combine(skillDir, WlPaths.SkillFileName);
        var existed = File.Exists(skillFile);
        Directory.CreateDirectory(skillDir);
        File.WriteAllText(skillFile, LoadResource(resourceName));
        return !existed;
    }

    private const string DefaultGitignore =
        """
        # Machine-local state — do not sync across PCs
        .last-session
        .last
        .version
        .paths.json
        .config.json

        # wl-managed skills — re-installed by `wl setup` on each PC
        .shared/.claude/skills/wl-create-workspace/
        .shared/.claude/skills/wl-update-workspace/

        # Auto-generated by `wl launch` for Copilot workspaces (mirror of
        # instructions.md — instructions.md is the source of truth)
        */AGENTS.md

        # Auto-generated plugin manifests for Copilot's --plugin-dir loader
        */.claude/plugin.json
        .shared/.claude/plugin.json

        # Added by `wl setup`
        """;

    public SetupResult RunSetup()
    {
        var previous = versionService.GetInstalledVersion();
        var current = versionService.GetCurrentVersion();

        var sharedSkills = paths.SharedSkillsDir;
        var createDir = WlPaths.Skill(sharedSkills, CreateSkillName);
        var updateDir = WlPaths.Skill(sharedSkills, UpdateSkillName);

        var createFresh = WriteSkill(createDir, $"{CreateSkillName}.md");
        var updateFresh = WriteSkill(updateDir, $"{UpdateSkillName}.md");

        // Migrate from earlier versions that installed wl-create-workspace
        // into the user's global Claude skills dir. wl owns this file; once
        // the new copy is in .shared/.claude/skills/, the legacy global
        // install would just shadow the same skill.
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        var legacyCreateDir = Path.Combine(home, ".claude", "skills", CreateSkillName);
        if (Directory.Exists(legacyCreateDir))
        {
            try { Directory.Delete(legacyCreateDir, recursive: true); }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException)
            {
                // Best effort — user can remove manually if needed. Surface the
                // reason so they aren't left wondering why a stale folder
                // remains under ~/.claude/skills/.
                Console.Error.WriteLine($"Warning: could not delete legacy {legacyCreateDir} ({ex.GetType().Name}); remove manually if desired.");
            }
        }

        // Migrate from versions that registered skill dirs in
        // ~/.copilot/settings.json. Skills are now loaded per-launch via
        // --plugin-dir, so any wl-managed entries left over there are dead
        // weight (and would silently leak skills into unrelated copilot
        // sessions). Strip entries pointing inside ~/.wl-workspaces/.
        StripStaleCopilotSkillDirs(home, paths.WorkspacesRoot);

        // Migrate per-workspace .last-session files from the legacy
        // bare-UUID format to the JSON map keyed by tool. Pre-0.8.0
        // stored one UUID per workspace, shared across all agents —
        // launching the same workspace in Copilot then Claude (or vice
        // versa) silently overwrote the previous agent's resume
        // pointer. The new format is { "copilot": "...", "claude":
        // "..." }; this pass converts any pre-existing bare UUID once,
        // attributing it to the workspace's resolved tool.
        MigrateLastSessionFiles();

        EnsureGitignore();

        versionService.StampVersion();
        return new SetupResult(createFresh, updateFresh, previous, current);
    }

    private static readonly string[] RequiredGitignorePatterns = DefaultGitignore
        .Split('\n')
        .Select(l => l.Trim())
        .Where(l => l.Length > 0 && !l.StartsWith('#'))
        .ToArray();

    private const string AddedByHeader = "# Added by `wl setup`";

    private void EnsureGitignore()
    {
        var gitignorePath = paths.GitignoreFile;
        if (!File.Exists(gitignorePath))
        {
            File.WriteAllText(gitignorePath, DefaultGitignore);
            return;
        }

        // Ensure every required pattern from DefaultGitignore is present in
        // the existing file. Older wl versions wrote a smaller template, so
        // upgrading users may be missing entries (e.g. wl-create-workspace/,
        // */AGENTS.md). Append only the missing ones — leave user edits
        // untouched.
        var existing = File.ReadAllText(gitignorePath);
        var existingPatterns = existing
            .Split('\n')
            .Select(l => l.Trim())
            .Where(l => l.Length > 0 && !l.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);

        var missing = RequiredGitignorePatterns
            .Where(p => !existingPatterns.Contains(p))
            .ToList();
        if (missing.Count == 0)
        {
            return;
        }

        File.WriteAllText(gitignorePath, MergeGitignore(existing, missing));
    }

    public static string MergeGitignore(string existing, IEnumerable<string> missing)
    {
        // Preserve the existing file's newline style (CRLF or LF) so a
        // wl-managed .gitignore synced across OSes via `wl clone` doesn't
        // churn every line on the next setup run. If the input doesn't
        // have a newline yet (empty/single-line), fall back to the
        // platform default.
        var newline = DetectNewline(existing);

        // Whitespace-only is treated as empty so a fresh file starts with
        // the header on line 1 (no leading blanks).
        var hasContent = !string.IsNullOrWhiteSpace(existing);
        var trimmed = hasContent ? existing.TrimEnd() : "";
        var lines = trimmed.Length == 0
            ? new List<string>()
            : trimmed.Split('\n').Select(l => l.TrimEnd('\r')).ToList();

        // The wl-managed block is identified by its header line ("# Added
        // by `wl setup`"). Past versions only handled the case where that
        // block sat at the end of the file — if a user added their own
        // lines below it, the next merge would emit a second header at
        // EOF and split wl's patterns across two blocks. Now we locate
        // the header anywhere and insert into the existing block.
        var headerIndex = lines.FindIndex(l => l.Trim() == AddedByHeader);
        if (headerIndex < 0)
        {
            // No managed block yet — append a fresh one. Only emit the
            // visual separator (blank line) when there's existing
            // content; otherwise an empty file would start with blank
            // lines before the header.
            var sb = new System.Text.StringBuilder();
            if (trimmed.Length > 0)
            {
                sb.Append(trimmed);
                sb.Append(newline).Append(newline);
            }
            sb.Append(AddedByHeader);
            foreach (var line in missing)
            {
                sb.Append(newline).Append(line);
            }
            sb.Append(newline);
            return sb.ToString();
        }

        // Walk forward from the header over non-blank lines; the next
        // blank (or EOF) marks the end of the managed block. Insert the
        // missing patterns right before that boundary.
        var insertAt = headerIndex + 1;
        while (insertAt < lines.Count && !string.IsNullOrWhiteSpace(lines[insertAt]))
        {
            insertAt++;
        }
        lines.InsertRange(insertAt, missing);

        return string.Join(newline, lines) + newline;
    }

    public static string DetectNewline(string content)
    {
        if (content.Contains("\r\n", StringComparison.Ordinal)) return "\r\n";
        if (content.Contains('\n')) return "\n";
        return Environment.NewLine;
    }

    public static void StripStaleCopilotSkillDirs(string home, string workspacesRoot)
    {
        var settingsPath = Path.Combine(home, ".copilot", "settings.json");
        if (!File.Exists(settingsPath))
        {
            return;
        }

        try
        {
            var settings = JsonNode.Parse(File.ReadAllText(settingsPath)) as JsonObject;
            if (settings is null || settings["skillDirectories"] is not JsonArray dirs || dirs.Count == 0)
            {
                return;
            }

            var prefix = workspacesRoot.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            var pathComparison = OperatingSystem.IsWindows()
                ? StringComparison.OrdinalIgnoreCase
                : StringComparison.Ordinal;
            var changed = false;
            for (var i = dirs.Count - 1; i >= 0; i--)
            {
                if (dirs[i] is JsonValue v && v.TryGetValue<string>(out var existing)
                    && existing.StartsWith(prefix, pathComparison)
                    && (existing.Length == prefix.Length
                        || existing[prefix.Length] == Path.DirectorySeparatorChar
                        || existing[prefix.Length] == Path.AltDirectorySeparatorChar))
                {
                    dirs.RemoveAt(i);
                    changed = true;
                }
            }

            if (!changed)
            {
                return;
            }

            var tmp = settingsPath + ".tmp";
            try
            {
                File.WriteAllText(tmp, settings.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
                File.Move(tmp, settingsPath, overwrite: true);
            }
            catch
            {
                // Don't leave a half-written .tmp behind if either the
                // write or the atomic move fails. Best effort — re-throw
                // so the outer catch surfaces a warning to the user.
                try { if (File.Exists(tmp)) File.Delete(tmp); } catch { /* swallowed */ }
                throw;
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException or JsonException)
        {
            // Best effort — never let migration break setup. Surface the
            // reason so users running into a locked or corrupted Copilot
            // settings file aren't left guessing.
            Console.Error.WriteLine($"Warning: could not migrate {settingsPath} ({ex.GetType().Name}); skill loading still works via --plugin-dir.");
        }
    }

    // One-time migration of per-workspace .last-session files from
    // the legacy bare-UUID format (one session id per workspace,
    // shared across all agents) to the JSON map keyed by tool name.
    // Idempotent: files already in JSON form are left alone, files
    // that don't parse as a UUID are skipped (LaunchService.Load
    // will treat them as no-session and start fresh).
    //
    // Public + static so it's unit-testable without standing up the
    // whole DI graph. The instance wrapper below pipes in the
    // workspaces root and the global default tool from ConfigService.
    public void MigrateLastSessionFiles()
    {
        MigrateLastSessionFiles(paths.WorkspacesRoot, config.DefaultTool);
    }

    public static void MigrateLastSessionFiles(string workspacesRoot, string? defaultTool)
    {
        if (!Directory.Exists(workspacesRoot))
            return;

        IEnumerable<string> workspaceDirs;
        try
        {
            workspaceDirs = Directory.EnumerateDirectories(workspacesRoot);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException)
        {
            Console.Error.WriteLine($"Warning: could not enumerate {workspacesRoot} ({ex.GetType().Name}); skipping .last-session migration.");
            return;
        }

        foreach (var workspaceDir in workspaceDirs)
        {
            // Skip the .shared/ sibling and other wl-internal dirs —
            // none of them have .last-session, but be defensive.
            if (Path.GetFileName(workspaceDir).StartsWith('.'))
                continue;

            var lastSessionPath = Path.Combine(workspaceDir, WlPaths.LastSessionFileName);
            if (!File.Exists(lastSessionPath))
                continue;

            try
            {
                var content = File.ReadAllText(lastSessionPath).Trim();

                // Already migrated (JSON), empty, or non-UUID corrupt — nothing to do.
                if (content.Length == 0 || content.StartsWith('{') || !Guid.TryParse(content, out _))
                    continue;

                // Attribute the bare UUID to the workspace's resolved
                // tool: workspace.json's `tool` field first, then the
                // global defaultTool, then "claude" (pre-0.8 wl was
                // Claude-only, so single-tool users get a correct
                // migration; cross-tool users had already lost data
                // under the legacy code).
                var wsTool = ReadWorkspaceTool(Path.Combine(workspaceDir, WlPaths.WorkspaceConfigFileName));
                var toolKey = (wsTool ?? defaultTool ?? "claude").ToLowerInvariant();
                var map = new Dictionary<string, string> { [toolKey] = content };
                var json = JsonSerializer.Serialize(map, WlJsonContext.Default.DictionaryStringString);

                var tmp = lastSessionPath + ".tmp";
                File.WriteAllText(tmp, json);
                try
                {
                    File.Move(tmp, lastSessionPath, overwrite: true);
                }
                catch
                {
                    try { File.Delete(tmp); } catch { /* swallowed */ }
                    throw;
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException or JsonException)
            {
                // Best effort — leave the file as-is and warn. The user
                // will start a fresh session on next launch.
                Console.Error.WriteLine($"Warning: could not migrate {lastSessionPath} ({ex.GetType().Name}); next --resume will start fresh.");
            }
        }
    }

    private static string? ReadWorkspaceTool(string workspaceJsonPath)
    {
        if (!File.Exists(workspaceJsonPath))
            return null;
        try
        {
            var ws = JsonSerializer.Deserialize(File.ReadAllText(workspaceJsonPath), WlJsonContext.Default.Workspace);
            return string.IsNullOrEmpty(ws?.Tool) ? null : ws.Tool;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException or JsonException)
        {
            return null;
        }
    }

    public bool EnsureInstalled()
    {
        var sharedSkills = paths.SharedSkillsDir;
        var skillsPresent =
            File.Exists(WlPaths.SkillFile(sharedSkills, CreateSkillName)) &&
            File.Exists(WlPaths.SkillFile(sharedSkills, UpdateSkillName));

        if (skillsPresent && versionService.GetInstalledVersion() == versionService.GetCurrentVersion())
        {
            return false;
        }

        var result = RunSetup();
        Console.WriteLine();
        Console.WriteLine(result.PreviousVersion is null
            ? "  First run: installed wl skills."
            : $"  Upgraded {result.PreviousVersion} → {result.CurrentVersion}: refreshed wl skills.");
        return true;
    }
}
