using System.Reflection;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace wl.Services;

public record SetupResult(bool CreateWorkspaceFresh, bool UpdateWorkspaceFresh, string? PreviousVersion, string CurrentVersion);

public class SetupService(WorkspaceService workspaces, VersionService versionService)
{
    private const string CreateSkillName = "wl-create-workspace";
    private const string UpdateSkillName = "wl-update-workspace";

    private static string LoadResource(string name)
    {
        using var stream = Assembly.GetExecutingAssembly()
            .GetManifestResourceStream($"wl.Resources.{name}")
            ?? throw new InvalidOperationException($"Missing embedded resource: {name}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static bool WriteSkill(string skillDir, string resourceName)
    {
        var skillFile = Path.Combine(skillDir, "SKILL.md");
        var existed = File.Exists(skillFile);
        Directory.CreateDirectory(skillDir);
        File.WriteAllText(skillFile, LoadResource(resourceName));
        return !existed;
    }

    private const string DefaultGitignore =
        """
        # Machine-local state — do not sync across PCs
        .last-session
        .last
        .version
        .paths.json
        .config.json

        # wl-managed skills — re-installed by `wl setup` on each PC
        .shared/.claude/skills/wl-create-workspace/
        .shared/.claude/skills/wl-update-workspace/

        # Auto-generated by `wl launch` for Copilot workspaces (mirror of
        # instructions.md — instructions.md is the source of truth)
        */AGENTS.md

        # Auto-generated plugin manifests for Copilot's --plugin-dir loader
        */.claude/plugin.json
        .shared/.claude/plugin.json
        """;

    public SetupResult RunSetup()
    {
        var previous = versionService.GetInstalledVersion();
        var current = versionService.GetCurrentVersion();

        var sharedSkills = workspaces.GetSharedSkillsPath();
        var createDir = Path.Combine(sharedSkills, CreateSkillName);
        var updateDir = Path.Combine(sharedSkills, UpdateSkillName);

        var createFresh = WriteSkill(createDir, $"{CreateSkillName}.md");
        var updateFresh = WriteSkill(updateDir, $"{UpdateSkillName}.md");

        // Migrate from earlier versions that installed wl-create-workspace
        // into the user's global Claude skills dir. wl owns this file; once
        // the new copy is in .shared/.claude/skills/, the legacy global
        // install would just shadow the same skill.
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        var legacyCreateDir = Path.Combine(home, ".claude", "skills", CreateSkillName);
        if (Directory.Exists(legacyCreateDir))
        {
            try { Directory.Delete(legacyCreateDir, recursive: true); }
            catch { /* best effort — user can remove manually if needed */ }
        }

        // Migrate from versions that registered skill dirs in
        // ~/.copilot/settings.json. Skills are now loaded per-launch via
        // --plugin-dir, so any wl-managed entries left over there are dead
        // weight (and would silently leak skills into unrelated copilot
        // sessions). Strip entries pointing inside ~/.wl-workspaces/.
        StripStaleCopilotSkillDirs(home, workspaces.GetWorkspacesRoot());

        EnsureGitignore();

        versionService.StampVersion();
        return new SetupResult(createFresh, updateFresh, previous, current);
    }

    private static readonly string[] RequiredGitignorePatterns = DefaultGitignore
        .Split('\n')
        .Select(l => l.Trim())
        .Where(l => l.Length > 0 && !l.StartsWith('#'))
        .ToArray();

    private const string AddedByHeader = "# Added by `wl setup`";

    private void EnsureGitignore()
    {
        var gitignorePath = Path.Combine(workspaces.GetWorkspacesRoot(), ".gitignore");
        if (!File.Exists(gitignorePath))
        {
            File.WriteAllText(gitignorePath, DefaultGitignore);
            return;
        }

        // Ensure every required pattern from DefaultGitignore is present in
        // the existing file. Older wl versions wrote a smaller template, so
        // upgrading users may be missing entries (e.g. wl-create-workspace/,
        // */AGENTS.md). Append only the missing ones — leave user edits
        // untouched.
        var existing = File.ReadAllText(gitignorePath);
        var existingPatterns = existing
            .Split('\n')
            .Select(l => l.Trim())
            .Where(l => l.Length > 0 && !l.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);

        var missing = RequiredGitignorePatterns
            .Where(p => !existingPatterns.Contains(p))
            .ToList();
        if (missing.Count == 0)
        {
            return;
        }

        File.WriteAllText(gitignorePath, MergeGitignore(existing, missing));
    }

    public static string MergeGitignore(string existing, IEnumerable<string> missing)
    {
        // If the file already ends with our managed "# Added by wl setup"
        // block, append patterns directly under it so multiple migration
        // runs don't litter the file with duplicate headers.
        var trimmed = existing.TrimEnd();
        var lines = trimmed.Split('\n').Select(l => l.TrimEnd('\r')).ToList();
        var blockStart = lines.Count;
        while (blockStart > 0 && !string.IsNullOrEmpty(lines[blockStart - 1]))
        {
            blockStart--;
        }
        var lastBlockIsOurs = blockStart < lines.Count && lines[blockStart] == AddedByHeader;

        var sb = new System.Text.StringBuilder(trimmed);
        sb.AppendLine();
        if (!lastBlockIsOurs)
        {
            sb.AppendLine();
            sb.AppendLine(AddedByHeader);
        }
        foreach (var line in missing)
        {
            sb.AppendLine(line);
        }
        return sb.ToString();
    }

    public static void StripStaleCopilotSkillDirs(string home, string workspacesRoot)
    {
        var settingsPath = Path.Combine(home, ".copilot", "settings.json");
        if (!File.Exists(settingsPath))
        {
            return;
        }

        try
        {
            var settings = JsonNode.Parse(File.ReadAllText(settingsPath)) as JsonObject;
            if (settings is null || settings["skillDirectories"] is not JsonArray dirs || dirs.Count == 0)
            {
                return;
            }

            var prefix = workspacesRoot.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            var changed = false;
            for (var i = dirs.Count - 1; i >= 0; i--)
            {
                if (dirs[i] is JsonValue v && v.TryGetValue<string>(out var existing)
                    && existing.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                {
                    dirs.RemoveAt(i);
                    changed = true;
                }
            }

            if (!changed)
            {
                return;
            }

            var tmp = settingsPath + ".tmp";
            File.WriteAllText(tmp, settings.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
            File.Move(tmp, settingsPath, overwrite: true);
        }
        catch
        {
            // Best effort — never let migration break setup.
        }
    }

    public bool EnsureInstalled()
    {
        var sharedSkills = workspaces.GetSharedSkillsPath();
        var skillsPresent =
            File.Exists(Path.Combine(sharedSkills, CreateSkillName, "SKILL.md")) &&
            File.Exists(Path.Combine(sharedSkills, UpdateSkillName, "SKILL.md"));

        if (skillsPresent && versionService.GetInstalledVersion() == versionService.GetCurrentVersion())
        {
            return false;
        }

        var result = RunSetup();
        Console.WriteLine();
        Console.WriteLine(result.PreviousVersion is null
            ? "  First run: installed Claude skills."
            : $"  Upgraded {result.PreviousVersion} → {result.CurrentVersion}: refreshed Claude skills.");
        return true;
    }
}
